# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    # Extract changelog section for this version and save to file
    # GORELEASER_CURRENT_TAG is set by goreleaser automatically
    - bash -c './scripts/extract-changelog.sh {{ .Tag }} > .release-notes.md'

builds:
  - main: ./cmd/brun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
      - riscv64
    ignore:
      - goos: windows
        goarch: arm

archives:
  - formats: ['binary']
    name_template: >-
      {{ .ProjectName }}-
      {{- .Tag }}-
      {{- if eq .Os "darwin" }}Macos
      {{- else }}{{ title .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  header: |
    ## Release Notes
  footer: |

    ---

    To update, run: `brun update`
  extra_files:
    - glob: .release-notes.md
