config:
  state_location: /tmp/brun-build-state.yaml

units:
  - start:
      name: build-trigger
      on_success:
        - format
        
  - run:
      name: format
      script: |
        go fmt ./...
      on_success:
        - test

  - run:
      name: test
      script: |
        echo "Running tests..."
        go test
      on_success:
        - build

  - run:
      name: build
      script: |
        echo "Building brun..."
        VERSION=$(git describe --tags HEAD 2>/dev/null || echo "dev")
        go build -ldflags "-X main.version=${VERSION}" -o brun ./cmd/brun
        echo "Build complete: brun version ${VERSION}"
