config:
  state_location: /tmp/brun-state.yaml

units:
  - start:
      name: start-trigger
      on_success:
        - build-unit

  - boot:
      name: boot-trigger
      on_success:
        - build-unit
      on_failure:
        - notify-admin
      always:
        - log-unit

  - run:
      name: build-unit
      script: |
        echo "Building project..."
        go build -o brun ./cmd/brun
        echo "Build complete"
      on_success:
        - test-unit
        - test-fail
      on_failure:
        - notify-admin

  - run:
      name: test-unit
      script: |
        echo "Running tests..."
        go test -v
        echo "Tests complete"
      on_failure:
        - notify-admin

  - run:
      name: test-fail
      script: |
        echo "fail script"
        exit -1
      on_failure:
        - log-error

  - log:
      name: log-error
      file: error.log

