config:
  state_location: /tmp/brun-state.yaml

units:
  - start:
      name: start-trigger
      on_success:
        - build-unit

  - boot:
      name: boot-trigger
      on_success:
        - build-unit
      on_failure:
        - notify-admin
      always:
        - log-unit

  - run:
      name: build-unit
      script: |
        echo "Building project..."
        go build -o brun ./cmd/brun
        echo "Build complete"
      on_success:
        - test-unit
        - test-fail
      on_failure:
        - notify-admin
      always:
        - count-builds

  - run:
      name: test-unit
      script: |
        echo "Running tests..."
        go test -v
        echo "Tests complete"
      on_failure:
        - notify-admin

  - run:
      name: test-fail
      script: |
        echo "fail script"
        exit -1
      on_failure:
        - log-error

  - log:
      name: log-error
      file: error.log

  - log:
      name: log-unit
      file: /tmp/brun-boot.log

  - count:
      name: count-builds

  - cron:
      name: periodic-check
      schedule: "*/5 * * * *"
      on_success:
        - test-unit

  - email:
      name: notify-admin
      to:
        - admin@example.com
      from: brun@example.com
      subject_prefix: "BRun Alert"
      smtp_host: smtp.example.com
      smtp_port: 587
      smtp_user: brun@example.com
      smtp_password: your-password-here
      smtp_use_tls: true
      include_output: true

  # Uncomment to enable automatic reboot (use with caution!)
  # - reboot:
  #     name: reboot-system
  #     delay: 5
