config:
  state_location: /tmp/simpleci-state.yaml

units:
  - boot:
      name: boot-trigger
      on_success:
        - build-unit
        - test-unit
      on_failure:
        - notify-admin
      always:
        - log-unit
